# -*- restclient -*-
# Emacs Commands:
# - C-c C-v - execute and keep focus
# - C-c C-g - start helm session
# - C-c C-n|p - jump to next | previous query
#
# SEE:
# - https://github.com/pashky/restclient.el
# - https://jakemccrary.com/blog/2014/07/04/using-emacs-to-explore-an-http-api/
##############################################################################
# API Documentation:
# -

:projecId = 2099
:api = https://freeway.porsche.org/api/v4/projects/:projetId/variables
:store = https://freeway.porsche.org/enablement/gitlab-vault/-/raw/main

# API:
GET :api/
PRIVATE-TOKEN: ${GITLAB_TOKEN}

# Store
GET :store/certificates/PD/testuserpos1.p12
